"""Trading signal domain models."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from enum import StrEnum
from typing import Any


def _as_decimal(value: object | None, *, field_name: str) -> Decimal:
    """Convert supported numeric inputs to Decimal while preserving validation."""
    if value is None:
        raise ValueError(f"{field_name} is required")
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value))
    except (ArithmeticError, InvalidOperation, TypeError, ValueError) as exc:
        raise ValueError(f"{field_name} must be a valid decimal value") from exc


class SignalValue(StrEnum):
    """Deterministic final trade signal."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradeSide(StrEnum):
    """Trade direction used for a proposed order."""

    LONG = "LONG"
    SHORT = "SHORT"


@dataclass(frozen=True, slots=True)
class SignalRequest:
    """Domain request for a single deterministic signal evaluation."""

    symbol: str
    timeframe: str = "1h"
    strategy: str | None = None
    account_equity: Decimal | None = None
    current_exposure: Decimal | None = None
    daily_loss: Decimal | None = None
    peak_equity: Decimal | None = None
    current_equity: Decimal | None = None
    open_positions: int | None = None
    strategy_parameters: dict[str, Any] = field(default_factory=dict)
    risk_configuration_overrides: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_mapping(cls, values: dict[str, Any]) -> SignalRequest:
        """Coerce API payload values into the domain request."""
        raw_strategy = values.get("strategy")
        return cls(
            symbol=str(values.get("symbol") or "").strip(),
            timeframe=str(values.get("timeframe") or "1h").strip() or "1h",
            strategy=str(raw_strategy).strip() if raw_strategy is not None else None,
            account_equity=(
                _as_decimal(values.get("account_equity"), field_name="account_equity")
                if values.get("account_equity") is not None
                else None
            ),
            current_exposure=(
                _as_decimal(values.get("current_exposure"), field_name="current_exposure")
                if values.get("current_exposure") is not None
                else None
            ),
            daily_loss=(
                _as_decimal(values.get("daily_loss"), field_name="daily_loss")
                if values.get("daily_loss") is not None
                else None
            ),
            peak_equity=(
                _as_decimal(values.get("peak_equity"), field_name="peak_equity")
                if values.get("peak_equity") is not None
                else None
            ),
            current_equity=(
                _as_decimal(values.get("current_equity"), field_name="current_equity")
                if values.get("current_equity") is not None
                else None
            ),
            open_positions=(
                int(str(values.get("open_positions")))
                if values.get("open_positions") is not None
                else None
            ),
            strategy_parameters=dict(values.get("strategy_parameters") or {}),
            risk_configuration_overrides=dict(values.get("risk_configuration_overrides") or {}),
        )

    def normalized_strategy_name(self, *, default: str = "moving_average_trend") -> str:
        """Normalize a strategy selection into the registry name."""
        selected = (self.strategy or default).strip()
        normalized = selected.lower().replace(" ", "_")
        aliases = {
            "moving_average": "moving_average_trend",
            "moving_average_trend": "moving_average_trend",
            "ma_trend": "moving_average_trend",
            "rsi": "rsi",
            "macd": "macd",
            "trend": "moving_average_trend",
        }
        return aliases.get(normalized, normalized)


@dataclass(frozen=True, slots=True)
class ProposedTrade:
    """Deterministic proposal before final risk validation."""

    symbol: str
    side: TradeSide
    entry_price: Decimal
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    strategy: str | None = None
    rationale: str = ""
    risk_reward_ratio: Decimal | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass(frozen=True, slots=True)
class TradingSignal:
    """Final, explainable trading signal generated by the signal engine."""

    signal: SignalValue
    symbol: str
    price: Decimal | None = None
    indicators: dict[str, str] = field(default_factory=dict)
    strategy: str = "moving_average_trend"
    confidence: Decimal = Decimal("0")
    entry: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    risk_reward_ratio: Decimal | None = None
    reasoning: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def signal_type(self) -> SignalValue:
        """Backwards-compatible alias for the signal value."""
        return self.signal

    @property
    def risk_reward(self) -> Decimal | None:
        """Alias for API compatibility."""
        return self.risk_reward_ratio


__all__ = [
    "ProposedTrade",
    "SignalRequest",
    "SignalValue",
    "TradeSide",
    "TradingSignal",
]
