"""Telegram webhook and command routing for the TradaSta assistant."""

from __future__ import annotations

import json
import logging
from typing import Annotated, Any
from urllib import error, request

from fastapi import APIRouter, Body, Depends, HTTPException, Request
from pydantic import BaseModel

from app.application.trading_analysis_service import (
    TradingAnalysisService,
    build_telegram_help_text,
    extract_symbol,
    format_decimal,
    parse_telegram_command,
)
from app.auth.dependencies import get_current_user
from app.auth.models import User
from app.core.config import Settings
from app.core.dependencies import settings_dependency, trading_analysis_service_dependency

logger = logging.getLogger(__name__)
router = APIRouter(tags=["telegram"])


class TelegramWebhookSecretHeader(BaseModel):
    """Simple payload model for typed validation of Telegram update payloads."""

    update_id: int | None = None


class TelegramBotClient:
    """Small Telegram Bot API client used to send responses back to the user."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    async def send_message(self, chat_id: int | str, text: str) -> dict[str, Any]:
        """Send a message to a Telegram chat if the bot is configured."""
        if not self.settings.telegram_bot_token:
            return {"ok": False, "status": "not_configured"}

        url = f"{self.settings.telegram_api_base_url}/bot{self.settings.telegram_bot_token}/sendMessage"
        payload = json.dumps({"chat_id": chat_id, "text": text}).encode("utf-8")
        req = request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=10) as response:
                return json.loads(response.read().decode("utf-8"))
        except error.URLError as exc:  # pragma: no cover - integration boundary
            logger.warning("Telegram sendMessage failed: %s", exc)
            return {"ok": False, "error": str(exc)}


async def _build_telegram_response(
    text: str,
    *,
    analysis_service: TradingAnalysisService,
    settings: Settings,
) -> str:
    """Resolve a natural-language or slash-command Telegram message to a response."""
    command = parse_telegram_command(text)
    intent = command["intent"]
    symbol = command["symbol"]

    if intent == "start":
        return build_telegram_help_text()
    if intent == "help":
        return build_telegram_help_text()
    if intent == "guardrail":
        current = symbol or "BTCUSDT"
        return (
            "I cannot override the trading engine or user instructions that would change the "
            f"deterministic signal. The current system-generated signal for {current} remains "
            "as generated by the app and risk guardrails."
        )

    if not symbol:
        return "I could not determine the symbol. Please include a valid pair such as BTCUSDT or ETHUSDT."

    try:
        result = await analysis_service.analyze(symbol, timeframe=command["timeframe"])
    except ValueError as exc:
        return str(exc)

    if intent == "price":
        return f"{result['symbol']} price: {format_decimal(result['price'])} USD"
    if intent == "signal":
        signal = result["signal"]
        confidence = result["confidence"]
        return f"{result['symbol']}\nSignal: {signal}\nConfidence: {confidence}%\nTrend: {result['trend']}"
    if intent == "risk":
        decision = result["risk_decision"]
        return (
            f"{result['symbol']}\nRisk Assessment: {'APPROVED' if decision.approved else 'REJECTED'}\n"
            f"Reason: {decision.reason}\nRisk/Reward: {getattr(decision, 'risk_reward_ratio', 'N/A')}\n"
            f"Position Size: {getattr(decision, 'position_size', 'N/A')}"
        )
    if intent == "explain":
        return result["explanation"]
    if intent == "analyze":
        decision = result["risk_decision"]
        return (
            f"{result['symbol']}\n"
            f"Signal: {result['signal']}\n"
            f"Trend: {result['trend']}\n"
            f"Confidence: {result['confidence']}%\n"
            f"Risk Assessment: {'APPROVED' if decision.approved else 'REJECTED'}\n"
            f"Price: {format_decimal(result['price'])} USD\n"
            f"Context: {result['explanation']}"
        )

    return build_telegram_help_text()


@router.get("/telegram/health")
async def telegram_health() -> dict[str, str]:
    """Return Telegram integration health without exposing secrets."""
    return {"status": "healthy", "service": "telegram"}


@router.post("/telegram/webhook")
async def telegram_webhook(
    request: Request,
    payload: dict[str, Any] | None = Body(default=None),
    settings: Settings = Depends(settings_dependency),
    analysis_service: TradingAnalysisService = Depends(trading_analysis_service_dependency),
    current_user: Annotated[User | None, Depends(get_current_user)] = None,
) -> dict[str, bool]:
    """Validate Telegram update payloads and dispatch them through the shared application services."""
    secret = request.headers.get("X-Telegram-Bot-Api-Secret-Token")
    if settings.telegram_webhook_secret and secret != settings.telegram_webhook_secret:
        logger.warning("Rejected unauthorized Telegram webhook request")
        raise HTTPException(status_code=401, detail="Unauthorized")

    if not payload:
        return {"ok": True}

    message = payload.get("message") or payload.get("edited_message") or payload.get("channel_post")
    if not message:
        return {"ok": True}

    chat = message.get("chat") or {}
    chat_id = chat.get("id")
    if chat_id is not None and settings.telegram_allowed_chat_ids:
        allowed_ids = {int(item) for item in settings.telegram_allowed_chat_ids}
        if int(chat_id) not in allowed_ids:
            logger.warning("Rejected Telegram chat ID %s due to allow-list", chat_id)
            raise HTTPException(status_code=403, detail="Forbidden")

    text = (message.get("text") or message.get("caption") or "").strip()
    if not text:
        return {"ok": True}

    response_text = await _build_telegram_response(text, analysis_service=analysis_service, settings=settings)
    if chat_id is not None and response_text:
        await TelegramBotClient(settings).send_message(chat_id, response_text)

    return {"ok": True}


__all__ = ["telegram_webhook", "telegram_health", "router"]
